# shellcheck shell=bash

__nu_direnv_overlay_quote_nu() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//$'\n'/\\n}
  printf '"%s"' "$value"
}

__nu_direnv_overlay_fail() {
  unset DIRENV_NU_OVERLAY_APPLY
  if [[ -n ${__NU_DIRENV_OVERLAY_DIR:-} ]]; then
    rm -f "$__NU_DIRENV_OVERLAY_DIR/apply.nu"
  fi
}

__nu_direnv_overlay_dir() {
  if [[ -z ${__NU_DIRENV_OVERLAY_DIR:-} ]]; then
    __NU_DIRENV_OVERLAY_DIR=$(mktemp -d "${TMPDIR:-/tmp}/nu-direnv-overlay.XXXXXXXXXX")
    chmod 700 "$__NU_DIRENV_OVERLAY_DIR"
  fi

  printf '%s\n' "$__NU_DIRENV_OVERLAY_DIR"
}

__nu_direnv_overlay_prefix() {
  if [[ -z ${__NU_DIRENV_OVERLAY_PREFIX:-} ]]; then
    local sum
    sum=$(printf '%s' "$PWD" | cksum)
    __NU_DIRENV_OVERLAY_PREFIX="nu-direnv-$(id -u)-${sum%% *}"
  fi

  printf '%s\n' "$__NU_DIRENV_OVERLAY_PREFIX"
}

__nu_direnv_overlay_path_id() {
  local path=$1
  local sum
  sum=$(printf '%s' "$path" | cksum)
  printf '%s' "${sum%% *}"
}

__nu_direnv_overlay_print_export_tracking() {
  local name

  # Record exported commands, aliases, and externs after the overlays load.
  # Nushell cleanup uses this to hide definitions that can remain visible after
  # `overlay hide` marks the overlay inactive.
  printf 'let nu_direnv_overlay_modules = ['
  for name in "${__NU_DIRENV_OVERLAY_INTERNAL_NAMES[@]}"; do
    printf '%s ' "$(__nu_direnv_overlay_quote_nu "$name")"
  done
  printf ']\n'

  cat <<'EOF'
$env.NU_DIRENV_OVERLAY_EXPORTS = (
  scope modules
  | where {|module| $module.name in $nu_direnv_overlay_modules }
  | each {|module|
      (
        ($module.commands | get name)
        ++ ($module.aliases | get name)
        ++ ($module.externs | get name)
        ++ ($module.constants | get name)
        ++ ($module.submodules | get name)
      )
    }
  | flatten
  | uniq
  | str join (char us)
)
EOF
}

__nu_direnv_overlay_generate_apply() {
  local dir apply active name internal_name path quoted_name quoted_path

  dir=$(__nu_direnv_overlay_dir)
  apply="$dir/apply.nu"

  mkdir -p "$dir"
  chmod 700 "$dir"

  {
    printf '# Generated by nu-direnv-overlay from %s\n' "$PWD"

    local i
    for i in "${!__NU_DIRENV_OVERLAY_NAMES[@]}"; do
      name=${__NU_DIRENV_OVERLAY_NAMES[$i]}
      internal_name=${__NU_DIRENV_OVERLAY_INTERNAL_NAMES[$i]}
      path=${__NU_DIRENV_OVERLAY_PATHS[$i]}
      quoted_name=$(__nu_direnv_overlay_quote_nu "$internal_name")
      quoted_path=$(__nu_direnv_overlay_quote_nu "$path")
      printf '# %s\n' "$name"
      printf 'overlay use --reload %s as %s\n' "$quoted_path" "$quoted_name"
    done

    active=
    for name in "${__NU_DIRENV_OVERLAY_INTERNAL_NAMES[@]}"; do
      if [[ -n $active ]]; then
        active+=";"
      fi
      active+="$name"
    done
    printf '$env.NU_DIRENV_OVERLAY_ACTIVE = %s\n' "$(__nu_direnv_overlay_quote_nu "$active")"
    __nu_direnv_overlay_print_export_tracking
  } >"$apply"

  export DIRENV_NU_OVERLAY_APPLY="$apply"
}

__nu_direnv_overlay_append() {
  local path=$1
  local logical_name
  logical_name=$(basename "$path")
  logical_name=${logical_name%.nu}

  if [[ ${#__NU_DIRENV_OVERLAY_NAMES[@]} -gt 0 ]]; then
    local i existing_path
    for i in "${!__NU_DIRENV_OVERLAY_NAMES[@]}"; do
      existing_path=${__NU_DIRENV_OVERLAY_PATHS[$i]}
      if [[ $existing_path == "$path" ]]; then
        __nu_direnv_overlay_generate_apply
        return 0
      fi
    done
  fi

  __NU_DIRENV_OVERLAY_NAMES+=("$logical_name")
  __NU_DIRENV_OVERLAY_INTERNAL_NAMES+=("$(__nu_direnv_overlay_prefix)-$(__nu_direnv_overlay_path_id "$path")")
  __NU_DIRENV_OVERLAY_PATHS+=("$path")
  __nu_direnv_overlay_generate_apply
}

__nu_direnv_overlay_abs() {
  local target=$1
  local dir base
  dir=$(dirname "$target")
  base=$(basename "$target")
  printf '%s/%s\n' "$(cd "$dir" && pwd -P)" "$base"
}

__nu_direnv_overlay_use_one() {
  local file=$1

  if [[ ! -f $file ]]; then
    log_error "nu overlay file not found: $file"
    __nu_direnv_overlay_fail
    return 1
  fi

  local abs
  abs=$(__nu_direnv_overlay_abs "$file")
  watch_file "$abs"
  __nu_direnv_overlay_append "$abs"
}

use_nu-overlay() {
  local file

  if [[ ${__NU_DIRENV_OVERLAY_INITIALIZED:-} != 1 ]]; then
    declare -ga __NU_DIRENV_OVERLAY_NAMES=()
    declare -ga __NU_DIRENV_OVERLAY_INTERNAL_NAMES=()
    declare -ga __NU_DIRENV_OVERLAY_PATHS=()
    __NU_DIRENV_OVERLAY_INITIALIZED=1
  fi

  if [[ $# -ne 1 ]]; then
    log_error "use nu-overlay: expected exactly one <path.nu>"
    __nu_direnv_overlay_fail
    return 1
  fi

  file=$1

  if [[ $file == *=* ]]; then
    log_error "use nu-overlay: explicit overlay names are not supported: $file"
    __nu_direnv_overlay_fail
    return 1
  fi

  case "$file" in
    *'*'* | *'?'* | *'['* | *']'*)
      log_error "use nu-overlay: globs are not supported: $file"
      __nu_direnv_overlay_fail
      return 1
      ;;
  esac

  __nu_direnv_overlay_use_one "$file" || return 1
}
